[package]
name = "stoked2d"
version = "0.1.0"
edition = "2021"

[profile.release]
# lto = "fat"
panic = "abort"

[dependencies]
egui_speedy2d = "0.4.0"
speedy2d = "1.12.0"
glam = "0.24.2"
lazy_static = "1.4.0"
atomic_float = "0.1.0"
rayon = "1.8.0"
colorgrad = "0.6.2"
atomic = "0.6.0"
approx = "0.5.1"
rand = "0.8.5"
spin_sleep = "1.1.1"
lindel = "0.1.1"
voracious_radix_sort = { version = "1.2.0", features = ["voracious_multithread"] }
mimalloc = { version = "*", default-features = false }
atomic_enum = "0.2.0"